### ISSUE TITLE
Support for single call to put with a lease?

### ISSUE THREAD

**Issue by mgates** [davissp14/etcdv3-ruby#89]
Hey - I was wondering if you'd be in favor of a method to do a `put` and generate a lease for it with one method call, maybe something like `conn.put_with_lease "foo", "bar", ttl: 60`, or maybe just another option on the current `put` method. This would be nice for me, but I also understand if you'd like the library to match the protocol semantics more closely.

**Comment by mgates** [comment]
Also, if you're interested in things like this, what about some helper methods like 'set-if-unset', 'compare-and-set', `delete-if-equal`, and so on?

**Comment by davissp14** [comment]
These kind of helpers should probably live in your application until there's a high enough demand for it.  With that being said, we should be looking to stay in-line with the official client drivers as much possible.

**Comment by mgates** [comment]
Cool - that makes sense. Would you be open to a /contrib section with some examples/mixins or maybe a documentation PR with some guides to composing more advanced operations and structures?

**Comment by davissp14** [comment]
A `/contrib` section is a neat idea. As long as they stay isolated and optional I am totally game for something like that.
